name: ESLint

on:
push:
  paths:
    - 'src/*'
    - 'package.json'
    - 'yarn.lock'
    - 'tsconfig.json'
pull_request:
  paths:
    - 'src/*'
    - 'package.json'
    - 'yarn.lock'
    - 'tsconfig.json'

jobs:
  lint:
    strategy:
      matrix:
        node: [ '12' ]
        os: [ macOS-latest ]

    name: lint on Node v${{ matrix.node }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@v1.1.2
      with:
        node-version: ${{ matrix.node }}
    - name: Linting
      run: |
        yarn
        yarn lint
      env:
        CI: true
